{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3de912b8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://localhost:8080/ (Press CTRL+C to quit)\n",
      "[2023-05-03 22:29:45,036] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\flask_cors\\extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\flask_cors\\decorator.py\", line 128, in wrapped_function\n",
      "    resp = make_response(f(*args, **kwargs))\n",
      "  File \"<ipython-input-1-7d3e77b856d8>\", line 20, in index\n",
      "    contacts = [contact for contact in contacts_cursor]\n",
      "  File \"<ipython-input-1-7d3e77b856d8>\", line 20, in <listcomp>\n",
      "    contacts = [contact for contact in contacts_cursor]\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\pymongo\\cursor.py\", line 1248, in next\n",
      "    if len(self.__data) or self._refresh():\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\pymongo\\cursor.py\", line 1139, in _refresh\n",
      "    self.__session = self.__collection.database.client._ensure_session()\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\pymongo\\mongo_client.py\", line 1740, in _ensure_session\n",
      "    return self.__start_session(True, causal_consistency=False)\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\pymongo\\mongo_client.py\", line 1685, in __start_session\n",
      "    self._topology._check_implicit_session_support()\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\pymongo\\topology.py\", line 538, in _check_implicit_session_support\n",
      "    self._check_session_support()\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\pymongo\\topology.py\", line 554, in _check_session_support\n",
      "    self._select_servers_loop(\n",
      "  File \"C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\pymongo\\topology.py\", line 238, in _select_servers_loop\n",
      "    raise ServerSelectionTimeoutError(\n",
      "pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 645292df1cc461eb3e199e79, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>\n",
      "127.0.0.1 - - [03/May/2023 22:29:45] \"\u001b[35m\u001b[1mGET / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, render_template, request, redirect, url_for\n",
    "from pymongo import MongoClient\n",
    "from flask_cors import CORS, cross_origin\n",
    "import json\n",
    "\n",
    "#creating flask instance\n",
    "app = Flask(__name__)\n",
    "CORS(app, support_credentials = True)\n",
    "\n",
    "#creating a connection with the mongodb server and setting up the db and collection which are to be used\n",
    "client = MongoClient()\n",
    "db = client['contacts_db']\n",
    "collection = db['contacts']\n",
    "\n",
    "#home page with all the contacts in the list(collection)\n",
    "@app.route('/')\n",
    "@cross_origin(supports_credentials = True)\n",
    "def index():\n",
    "    contacts_cursor = collection.find()\n",
    "    contacts = [contact for contact in contacts_cursor]\n",
    "    json_contacts = json.dumps(contacts, default=str)\n",
    "    return render_template('index.html', contacts=json_contacts)\n",
    "\n",
    "#adding a contact into the collection\n",
    "@app.route('/add', methods=['GET', 'POST'])\n",
    "@cross_origin(supports_credentials = True)\n",
    "def add():\n",
    "    if request.method == 'POST':\n",
    "        contact = {\n",
    "            'name': request.form['name'],\n",
    "            'email': request.form['email'],\n",
    "            'phone': request.form['phone']\n",
    "        }\n",
    "        collection.insert_one(contact)\n",
    "        return redirect(url_for('index'))\n",
    "    return render_template('add.html')\n",
    "\n",
    "# #editing a contact according to the user's needs\n",
    "# @app.route('/edit/<id>', methods=['GET', 'POST'])\n",
    "# @cross_origin(supports_credentials = True)\n",
    "# def edit(id):\n",
    "#     contact = collection.find_one({'_id': ObjectId(id)})\n",
    "#     if request.method == 'POST':\n",
    "#         collection.update_one({'_id': ObjectId(id)}, {'$set': {\n",
    "#             'name': request.form['name'],\n",
    "#             'email': request.form['email'],\n",
    "#             'phone': request.form['phone']\n",
    "#         }})\n",
    "#         return redirect(url_for('index'))\n",
    "#     return render_template('edit.html', contact=contact)\n",
    "\n",
    "# #deleting a contact from the contact list\n",
    "# @app.route('/delete/<id>', methods=['POST'])\n",
    "# @cross_origin(supports_credentials = True)\n",
    "# def delete(id):\n",
    "#     collection.delete_one({'_id': ObjectId(id)})\n",
    "#     return redirect(url_for('index'))\n",
    "\n",
    "app.run(host = \"localhost\",port=8080)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "adc93710",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
